name: Build Release Zip

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create zip file
        run: |
          mkdir -p release/plugins
          cp your_python_file.py release/plugins/
          cp -r modules release/
          cd release
          zip -r myplugin.zip .

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: release/myplugin.zip
